version: "3"

tasks:
    build:
        desc: Build the go binary
        cmds:
        - go build -o phrame main.go

    run: 
        desc: Run the app
        cmds:
        - go run main.go
        
    test:
        desc: Test the app
        cmds:
        - go run main.go -i test -o out
    
    global:
        desc: Set the command as a global command
        cmds:
        - sudo mv phrame /usr/local/bin/
    